### ISSUE TITLE
Create a .gitignore file for the repo

### ISSUE THREAD

**Issue by davidtollefson** [davidtollefson/ICS4U#16]

**Comment by davidtollefson** [comment]
We want to make sure we don't include all the "bloat" for our project - this includes a number of things... Which we'll discuss.

**Comment by davidtollefson** [comment]
This is an excellent .gitignore file... Lets try to incorporate it.

https://gist.github.com/santoshpurbey/6f982faf1eacdac153ffd86a3a694239

**Comment by liammuir** [comment]
ok
