### ISSUE TITLE
Install the required requirements for our Django project

### ISSUE THREAD

**Issue by davidtollefson** [davidtollefson/ICS4U#17]
django
django-cors-header
djangorestframework

Also update settings.py

Please include a requirements.txt as we will not be uploading these packages to our repo.

**Comment by liammuir** [comment]
should i do this in a virtual env?

**Comment by davidtollefson** [comment]
This issue has not been assigned at this point. Please do not complete it.

**Comment by davidtollefson** [comment]
Steps required:

1) Create a virtual environment (either 'env' or 'venv')
2) Activate the environment
2) Install the 3 requirements
3) Pip freeze thing...
4) push those committed changes.
