### ISSUE TITLE
Liam - Test State of Repo

### ISSUE THREAD

**Issue by davidtollefson** [davidtollefson/ICS4U#30]
Destroy all the installs in your virtual environment

Pull from the repo

Install all dependencies using the requirements.txt file

Confirm project executes on your local machine.

**Comment by liammuir** [comment]
k

**Comment by liammuir** [comment]
While the application starts, the urls are misconfigured and the default page shows up

**Comment by davidtollefson** [comment]
Does the behavior match what's expected from the code in the repo?

**Comment by liammuir** [comment]
no

**Comment by davidtollefson** [comment]
Sure looks like it to me. Take a look at the urls.py file.

**Comment by liammuir** [comment]
i did and the contents are not functional, its all boiler plate

**Comment by davidtollefson** [comment]
Right, but does your local code match the code in the repo, and produce the behavior as expected from the code in the repo?

**Comment by liammuir** [comment]
ok my repositories behavior matches the spec so far

**Comment by davidtollefson** [comment]
Booyay
