### ISSUE TITLE
Create urls and views

### ISSUE THREAD

**Issue by davidtollefson** [davidtollefson/ICS4U#34]
2 urls are required:

api/students/
api/students/([0-9])

The first url with route to students_list
The second url will route to students_detail

You can find the implementation for these in your previous code.

Blocked by #31 and #32 - be sure to merge these two into your branch.

**Comment by AsherWentworth** [comment]
Do I need to modify views.py with temporary views, or just add URLs to urlpatterns?

**Comment by davidtollefson** [comment]
You should create the proper views themselves.
