### ISSUE TITLE
Create react application

### ISSUE THREAD

**Issue by davidtollefson** [davidtollefson/ICS4U#36]
Call it front-end

You'll need to install a few packages too:

npm install bootstrap reactstrap axios --save

**Comment by davidtollefson** [comment]
Git should ignore all those node_modules, but should capture the dependencies in package.json

**Comment by liammuir** [comment]
ok

**Comment by liammuir** [comment]
where do i put it

**Comment by davidtollefson** [comment]
Directly inside the StudentTracker Folder (the 1st one). The Front-end folder you end up creating should sit next to manage.py, or at the same level as.
